### PR TITLE
Use filter for logical OR in Makefile

### PR DESCRIPTION
**Pull request by davidgaspardev**
Can use filter function to simulate a logical OR with ifneq.

See here: https://lists.gnu.org/archive/html/make-w32/2004-03/msg00062.html

### CODE REVIEW

**Comment by dfunckt** [comment]
Hi @davidgaspardev, thanks a lot for the PR. Do you mind amending the commit message like so?

```
refactor: use filter for logical OR in Makefile

Can use filter function to simulate a logical OR with ifneq.

Change-type: patch
```

**Comment by dfunckt** [comment]
BTW, I rebased your branch over master for you, make sure to pull first.

**Comment by davidgaspardev** [comment]
@dfunckt, I apologize for the confusion, but it appears that there is still an issue with the workflow. Could you please elaborate on your previous instructions, or perhaps provide some additional guidance to help resolve this problem? Thanks!

**Comment by aethernet** [comment]
@davidgaspardev 

You need in one of your commit ending with a line with `Change-type: patch`

Another (maybe easier) solution is to prefix the title of one of your commit with `patch: ` (i.e. `patch: refactor: use filter for logical OR in Makefile`

**Comment by dfunckt** [comment]
Superseded by #4132

**Pull request closed without merging**
