### PR TITLE
Update link of electron-supported-platforms in README.md

### PR DESCRIPTION
**Pull request by PeterDaveHello**
This doc has moved for a while ;)

### CODE REVIEW

**Comment by dfunckt** [comment]
Hey @PeterDaveHello -- thanks for the PR. Etcher is currently stuck at an older Electron version so links to their docs for the supported platforms are misleading -- for example, we currently do not provide Apple Silicon builds, despite what their docs says. I'd much rather you deleted the complete `Note:` about supported platforms and the link -- the list of actually supported platforms is provided just above that note.

**Comment by dfunckt** [comment]
BTW, make sure to provide a `Change-type` with your commit message so that the PR becomes mergeable. For example, here is how to format a commit message that is acceptable by our CI:

```
Updated foo with bar

Change-type: patch
```

**Comment by dfunckt** [comment]
Superseded by #4132

**Comment by PeterDaveHello** [comment]
Oh, sorry that I didn't notice and revise on time, but it's good to see some updates here.

**Pull request closed without merging**
