### PR TITLE
Update resin-corvus to 2.0.5

### PR DESCRIPTION
**Pull request by thundron**
Change-type: patch
Changelog-entry: Update resin-corvus to 2.0.5
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzothunder.ambrosi@gmail.com>

### CODE REVIEW

**Comment by zvin** [comment]
@balena-ci retest

**Comment by thundron** [comment]
@balena-ci retest

**Comment by thundron** [comment]
@balena-ci retest

**Comment by thundron** [comment]
@balena-ci retest

**Pull request merged**
