### PR TITLE
Delete versionist.conf

### PR DESCRIPTION
**Pull request by nazrhom**
Versionist will now look at repo.yml and inject the versionist config
corresponding to the type

Change-type: patch
Changelog-Entry: Reformat changelog
Signed-off-by: Giovanni Garufi <giovanni@balena.io>

### CODE REVIEW

**Comment by lurch** [comment]
> Versionist will now look at repo.yml and inject the versionist config corresponding to the type

Oh? https://github.com/balena-io/versionist/search?q=repo.yml&unscoped_q=repo.yml
Is there a private version of versionist, or is reading repo.yml done by some other CI process and not `versionist` ?

**Comment by nazrhom** [comment]
@lurch yup we have https://github.com/balena-io/balena-versionist which is simply a layer that injects the correct versionist.conf based on the project type

**Comment by lurch** [comment]
Oooh, funky. So I guess that means that you (theoretically) should have said "balena-versionist will now look at repo.yml and inject the versionist config corresponding to the type" :wink: :laughing:

**Comment by zvin** [comment]
Cherry-picked in #2717

**Pull request closed without merging**
