### PR TITLE
Remove etcher-cli

### PR DESCRIPTION
**Pull request by zvin**
Change-type: major

### CODE REVIEW

**Comment by lurch** [comment]
Oh! Will https://www.balena.io/etcher/cli be disappearing too? (and BTW, the "report issues" link on that page is broken)

**Comment by RobertCNelson** [comment]
Why was this removed? It made things so much more useful when jumping between beaglebone images and was better than bmap-tools which needed a *.bmap file (bmap-tools is only cli based)..  I guess i better re-enable *.bmap files for beagleboard.org

YUCK!  Please revert this..

Regards,

**Comment by lurch** [comment]
In theory, writing a .bmap file (if it was properly created) can/should be faster than writing a .img file. And Etcher also supports writing bmaps. See #2128

**Comment by LongLiveCHIEF** [comment]
In fact, the UI never works at all, on Windows _or_ Linux (as admin or regular user), and the only way I was able to create images with etcher was with the cli.

👎

**Comment by lurch** [comment]
"In fact, the UI never works at all..."

I'm sure thousands of people would disagree with you :wink: 
Have you created an issue describing your problem in more detail?

**Comment by LongLiveCHIEF** [comment]
Trying to narrow it down. I've ruled out some of the existing known issues
(like docker running). I wound up having to re-install both Windows and
Ubuntu shortly after leaving this comment, and have since used etcher via
the UI just fine on Windows.

I haven't re-installed all my normal suite of tools yet, so I'll keep
checking it as I go to see if something causes a conflict.

Etcher logs were non-deterministic at the time.  I even used a different
USB drive, so I literally wiped the slate clean.

My gut tells me it could actually be the drive that was causing the
problem, but I haven't tested it since.

**Comment by rikvermeer** [comment]
I loved this product for the cli... back to dd :'(

goodbye my lover <3
hope to see you back

**Comment by NicolasDorier** [comment]
Is there any other alternative to flash an image in cli?

**Comment by thundron** [comment]
@NicolasDorier you can use examples from [etcher-sdk](https://github.com/balena-io-modules/etcher-sdk), they're not fully documented yet but you can give them a try (cc @rikvermeer in case you want to give it a try too)

**Comment by NicolasDorier** [comment]
@thundron I replaced by using `dd bs=8M "if=$IMAGE" "of=/dev/sdx"` it does not check integrity though.

**Pull request merged**
