### PR TITLE
v1.4.8

### PR DESCRIPTION
**Pull request by thundron**
### Features

- Added featured-project while flashing

### Fixes

- Moved back the write cancel button
- Reject drives with null size (fixes pretty-bytes error)

**PR Checklist:**

* [x]  Bump the version number in the `package.json`'s `version` property
* [x]  Bump the version number in the `npm-shrinkwrap.json`'s `version` property
* [x]  Add a new entry to `CHANGELOG.md` by running `make changelog`
* [x]  Update `screenshot.png`, so it displays the latest version in the bottom right corner
* [x]  Revise the `updates.semverRange` version in `package.json`
* [x]  Revise `CHANGELOG.md`

**Release Checklist:**

* [x]  Manual regression testing
* [ ]  Merge this
* [ ]  Tag the commit on master
* [ ]  Forum post
* [ ]  Update Etcher website
* [ ]  Mailing List update

### CODE REVIEW

**Comment by anuejn** [comment]
i think, that this is a highly critical change. 
it takes the ability to use etcher in tutorials, whose target audience is non makers, because it causes a lot of confusion and distraction.

I really like etcher, because it greatly simplifies the process of burning images for non linux experts.
Please remove this "feature" again in your release builds.

**Comment by thundron** [comment]
@anuejn We're working on making it less intrusive as we read from users feedback, so that makers or anyone who still wants to access those news can still see it

**Comment by anuejn** [comment]
nice, thanks!
i would suggest to disable it by default and add a checkbox to the settings page, where users can enable it.

**Comment by alexandrosm** [comment]
Hey there. The balena team started and to this day develops etcher, paying full time developers, servers, bandwidth, etc, while fully open sourcing the project and offering it for free to everyone. 

We're trying to find a model that justifies us continuing to spend hundreds of thousands of dollars a year on development of etcher while keeping it free and open source. We feel that the featured project is interesting to the maker audience (this isn't exactly a McDonald's ad) while helping us at balena promote our other products which are also very interesting to the same folks that use etcher. As a data point, many many people read the project page every day, and many hundreds have signed up and are building projects with balena cloud. This confirms for us that the featured project is I feed useful and interesting.

The next steps we want to make is to feature third party projects, not just ones made by the balena team.

We also want to continue to iterate on the UI to make it blend better, we know there's usability concerns, this is still an early phase of the effort.

**Comment by u451f** [comment]
@alexandrosm thank you for the detailed reply. I understand the idea of being financed and featuring other projects. Thanks for considering reworking the UI. I'm a tiny bit more concerned about tracking by these ads. Now, every time a user runs the program, there are outgoing connections. Where do they go to? What do you do with the data? How can users get back the control over those?

**Pull request merged**
