### PR TITLE
patch: Select drive on list interaction rather than modal closing

### PR DESCRIPTION
**Pull request by thundron**
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzothunder.ambrosi@gmail.com>

### CODE REVIEW

**Comment by thundron** [comment]
@balena-ci retest

**Comment by thundron** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by thundron** [comment]
@balena-ci retest

**Comment by thundron** [comment]
@balena-ci retest

**Comment by thundron** [comment]
@balena-ci retest

**Comment by thundron** [comment]
@balena-ci I self-certify!

**Pull request merged**
