### PR TITLE
Direct IO

### PR DESCRIPTION
**Pull request by zvin**

### CODE REVIEW

**Comment by zvin** [comment]
@balena-ci retest

**Comment by zvin** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by lurch** [comment]
Will this fix the issue where (at least on Linux) if you have loads of free memory, when Etcher tries to verify the image it's just written, it just verifies the in-memory disk buffers (at a ridiculous speed) rather than reading back the data that _actually_ got written to disk? (IYSWIM)

Ah, found #1523 which describes the problem in more detail :slightly_smiling_face:

**Comment by zvin** [comment]
@lurch yes

**Pull request merged**
