### PR TITLE
Patch: update etcher-sdk version to fix CM4 issues

### PR DESCRIPTION
**Pull request by builder555**
Change-type: patch

### CODE REVIEW

**Review by mcraa — APPROVED** [review]

**Comment by lurch** [comment]
Does this fix #3792 ?

**Comment by builder555** [comment]
@lurch in theory, yes, but i don't have a CM4 to test, so I'm waiting for someone with a module to give me the "ok"

**Comment by boedy** [comment]
@builder555 Just tried out release 1.13.1. Before Etcher would hang when inserting a newer CM4. With this release it seems to progress, but it eventually disappears. See screen recording below.

https://user-images.githubusercontent.com/2030968/210998719-916070f7-7e51-447d-882b-25a081df1654.mov

**Comment by builder555** [comment]
Thanks @boedy for testing, we'll be looking into it.

**Comment by boedy** [comment]
I'm using Waveshares - Mini Base Board (A)

**Pull request merged**
