### PR TITLE
Fix start script

### PR DESCRIPTION
**Pull request by zvin**
Replaces #3075

### CODE REVIEW

**Comment by thundron** [comment]
@balena-ci retest

**Comment by lurch** [comment]
Just to keep everything nicely interlinked... this fixes #3074

**Comment by zvin** [comment]
merged, thanks again @aloisklink

**Comment by aloisklink** [comment]
No worries! Thanks for making such a useful software opensource!

**Comment by lurch** [comment]
@thundron @zvin The bintray repository seems to be working again now, so I guess #3078 can be closed? :slightly_smiling_face: 

However it would also be nice if you could push a newer version to the repo, so that the people who _are_ using the repo pick up the fix in this PR :+1:

**Comment by lurch** [comment]
> @thundron @zvin The bintray repository seems to be working again now, so I guess #3078 can be closed? :slightly_smiling_face: 

I can't leave that as a comment on #3078 itself because it's been locked... :lock:

**Pull request merged**
