### PR TITLE
Update sudo-prompt to ^9.0.0

### PR DESCRIPTION
**Pull request by zvin**
Change-type: patch
Changelog-entry: Update sudo-prompt to ^9.0.0

### CODE REVIEW

**Comment by koyuawsmbrtn** [comment]
This patch makes my current installation of balena Etcher fail. I downgraded to 1.5.49 now as this version is the only one that's currently working for me.

**Comment by zvin** [comment]
@koyuawsmbrtn What OS are you using? What is the error? When does it happen?

**Comment by koyuawsmbrtn** [comment]
> @koyuawsmbrtn What OS are you using? What is the error? When does it happen?

Arch Linux with vanilla KDE, It just says "Something went wrong - Failed to flash" or something like that. The AUR-version seems to work for now, but the AppImage version is broken. It happens when I click on the flash button and entered my password.

**Comment by zvin** [comment]
@koyuawsmbrtn I just tried the Etcher 1.5.51 x64 AppImage on Arch, I couldn't reproduce the issue, it flashed fine.
Where did you save the AppImage?

**Comment by koyuawsmbrtn** [comment]
> @koyuawsmbrtn I just tried the Etcher 1.5.51 x64 AppImage on Arch Linux (with KDE), I couldn't reproduce the issue, it flashed fine.
> Where did you save the AppImage?

I saved it under ~/Applications

**Pull request merged**
