### PR TITLE
Update copyright year in .resinci.json

### PR DESCRIPTION
**Pull request by lurch**

### CODE REVIEW

**Comment by thundron** [comment]
@balena-ci retest

**Comment by lurch** [comment]
If you need to close my PR and perform these changes yourself in a separate PR for CI reasons, feel free to do so.

**Comment by thundron** [comment]
probably 🤷‍♂️ we were testing some changes in the CI, but then noticed that the `Change-type` and `Changelog-entry` tags were missing in the commits

**Comment by zvin** [comment]
cherry-picked in #3432

**Pull request closed without merging**
