### PR TITLE
Update to README.md

### PR DESCRIPTION
**Pull request by TheRealTachyon**
Just a simple addition of instructionsfor proper installation on OpenSUSE Linux.

### CODE REVIEW

**Comment by TheRealTachyon** [comment]
This seems like a pretty simple and innocuous change so I'm just curious why this hasn't been reviewed and approved yet? I haven't made a public GIT merge request before so if I've done something wrong I'd like to know so I can learn/fix it.

Thanks!!

**Comment by zvin** [comment]
https://balena.io/etcher/static/etcher-rpm.repo points to https://rpm.etcher.io which redirects to https://dl.bintray.com/etcher/redhat/

The last release on https://dl.bintray.com/etcher/redhat/ is `v1.5.51` which is quite old.
I'm not sure we still use this.
You can get the `rpm`s from github releases: https://github.com/balena-io/etcher/tags .

cc @thundron

**Comment by lurch** [comment]
> I'm not sure we still use this.

There's nothing at https://github.com/balena-io/etcher#redhat-rhel-and-fedora-based-package-repository-gnulinux-x86x64 (or https://github.com/balena-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64 , which I assume gets updated at the same time?) to indicate that they're not being used / updated? :man_shrugging: :man_shrugging:

**Comment by thundron** [comment]
Yes we use it, I'm updating just now. We need to make it sync with github releases

**Comment by zvin** [comment]
added in #3140 , thanks @TheRealTachyon

**Pull request closed without merging**
