### PR TITLE
Update etcher-sdk to ^4.1.3 to fix issues with some bz2 files

### PR DESCRIPTION
**Pull request by zvin**
Changelog-entry: Update etcher-sdk to ^4.1.0 to fix issues with some bz2 files
Change-type: patch

### CODE REVIEW

**Comment by zvin** [comment]
This should fix #3138

**Comment by zvin** [comment]
@balena-ci retest

**Comment by zvin** [comment]
@balena-ci retest

**Comment by zvin** [comment]
@balena-ci retest

**Comment by zvin** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by zvin** [comment]
@balena-ci retest

**Pull request merged**
