### PR TITLE
patch: update winget-releaser v2

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@aethernet any update on this?

**Comment by dfunckt** [comment]
Superseded by #4132

**Comment by vedantmgoyal2009** [comment]
@dfunckt that pr doesn't do the version bump

**Comment by dfunckt** [comment]
Indeed @vedantmgoyal2009, I only touched the regex in the end even though I meant to update it as well.

Do you mind rebasing? I’ll get to it and merge later today.

**Comment by vedantmgoyal2009** [comment]
@dfunckt rebased 👍

**Review by dfunckt — APPROVED** [review]

**Pull request merged**
