### PR TITLE
Update macOS Icon to Big Sur Style

### LINKED ISSUE #3603: New Icon for macOS Big Sur
macOS Big Sur introduced a new icon style (square icons instead of round icons). It would be great if BalenaEtcher had a new icon to agree with this design scheme. I know some individual users have already created their own versions of a square Etcher icon here: https://macosicons.com

### PR DESCRIPTION
**Pull request by Logicer16**
Closes #3603 

Replaces the old macOS icon with a new one provided by @thundron in #3603 and adds scaled icon sizes

### CODE REVIEW

**Comment by thundron** [comment]
remember to include a `Chante-type: patch` footer in your commit

**Comment by Logicer16** [comment]
@thundron Thanks for pointing that out. Should be fixed now.

**Review by thundron — APPROVED** [review]

**Comment by thundron** [comment]
lgtm, let's see what the maintainers say 👍

**Comment by lurch** [comment]
> lgtm, let's see what the maintainers say

Oh, I didn't realise you were no longer a maintainer @thundron ?

**Comment by thundron** [comment]
that's right @lurch 👀

**Comment by thundron** [comment]
just an aficionado :)

**Pull request merged**
