### PR TITLE
Use https for fetching sub modules

### PR DESCRIPTION
**Pull request by Jacalz**
This switches over the sub module to using https instead of ssh. It simplifies a lot for people packaging the application and you won't need to have ssh configured correctly. 👍

### CODE REVIEW

**Comment by Jacalz** [comment]
Could anybody please have a look at this? Without this, Etcher can't be built for the Solus operati9ng system, which is a real bummer!

**Comment by Jacalz** [comment]
Pinging @thundron on this :+1:

**Comment by thundron** [comment]
@Jacalz We're checking if it creates any issues with people that use two-factor auth

**Comment by Jacalz** [comment]
I am pretty certain that it doesn’t, you don’t need to be logged in for it to fetch sub modules, I think...

**Comment by thundron** [comment]
Trying it now, I'll let you know in some minutes 👍 (for cloning you shouldn't need auth, but better be safe)

**Comment by Jacalz** [comment]
This is rebased against master now :+1:
You are free to merge when you have time :slightly_smiling_face:

**Comment by thundron** [comment]
@resin-ci retest

**Comment by thundron** [comment]
@resin-ci retest

**Pull request merged**
