### PR TITLE
Catch console log messages from SafeWebView

### PR DESCRIPTION
**Pull request by roman-mazur**
This simplifies debugging of the content loaded by Etcher,
including analysis of loaded analytics libraries.

Change-type: patch
Signed-off-by: Roman Mazur <roman@balena.io>

### CODE REVIEW

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Comment by zvin** [comment]
@roman-mazur you need to add a `Changelog-entry: ` line to the commit message

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Comment by roman-mazur** [comment]
Thanks for merging :)

**Pull request merged**
