### PR TITLE
Use core workflow for GitHub publish

### PR DESCRIPTION
**Pull request by ab77**
Ideally wait for https://github.com/product-os/flowzone/pull/355

Note: switched branches while in flight, comments below relate to another PR.

### CODE REVIEW

**Comment by ab77** [comment]
@builder555 @mcraa @zwhitchcox

So it looks like the main common culprit to getting a working arm64 build for Etcher is `ronomon/direct-io`:

macOS-arm64 (electron-builder error):

```
fatal error: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/electron-universal-92tV9I/Tmp.app/Contents/Resources/app/generated/modules/@ronomon/direct-io/binding.node and /Users/runner/work/etcher/etcher/dist/mac-universal--arm64/balenaEtcher.app/Contents/Resources/app/generated/modules/@ronomon/direct-io/binding.node have the same architectures (x86_64) and can't be in the same fat output file
```

Windows-arm64 (dev tools console error)

```
Uncaught Error: \\?\C:\Users\belodetek\AppData\Local\Programs\balena-etcher\resources\app\generated\modules\@ronomon\direct-io\binding.node is not a valid Win32 application.
\\?\C:\Users\belodetek\AppData\Local\Programs\balena-etcher\resources\app\generated\modules\@ronomon\direct-io\binding.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5)
    at Module.load (internal/modules/cjs/loader.js:935)
    at Module._load (internal/modules/cjs/loader.js:776)
    at Function.f._load (electron/js2c/asar_bundle.js:5)
    at Function.o._load (electron/js2c/renderer_init.js:33)
    at Module.require (internal/modules/cjs/loader.js:959)
    at require (internal/modules/cjs/helpers.js:88)
    at Object.<anonymous> (gui.js:1)
```

Hopefully we can get that dependency updated/built for multiple architectures. Could be also as simple as webpack picking up the wrong binaries?

**Comment by theofficialgman** [comment]
fyi you are going to have a bad time with this because there are multiple BAD node packages that put x86_64 binaries inside their arm64 folder... one example is the `lzma-native` node module does this on all OSs 😢. its been reported for years and still goes unfixed by the dev

**Comment by ab77** [comment]
> you won't realize this is an issue until you actually go to launch etcher and you whitescreen and check the developer console for the log

Oh yes - we know, thank you! This is exactly where we are with this PR at the moment... @theofficialgman

**Comment by ab77** [comment]
@balena-ci I self-certify!

**Pull request merged**
