### PR TITLE
Update link to moved SUPPORT.md

### PR DESCRIPTION
**Pull request by olyop**
Updates the link of the help button to the moved SUPPORT.md markdown file.

Screenshot from 2023-03-05 12-42-46

### CODE REVIEW

**Review by servusdei2018 — APPROVED** [review]

**Comment by servusdei2018** [comment]
Actually just noticed the same issue today. Glad you patched it so quickly 👍🏽

**Comment by dfunckt** [comment]
@olyop thank you for the PR. Can you please rebase and squash your commits with a message and description similar to the following to get the CI going?

```
Fix URL of help button in UI

Change-type: patch
```

**Comment by lurch** [comment]
@dfunckt I wonder if there should be some kind of redirect or pointer at the _old_ URL, for the benefit of all the people using old versions of Etcher? :man_shrugging:

**Comment by olyop** [comment]
@dfunckt I'm not too familiar with git (we use svn at work) so not sure how to change the message of previous commits. Could you help me out here?

@lurch I added a symbolic link which should point the user in the right direction at least but there should be a better option.

**Comment by rodrigoreis** [comment]
Still broken

**Comment by aethernet** [comment]
Hello, 

I'll create a new PR for this and cherry pick your changes.

**Comment by aethernet** [comment]
replaced by https://github.com/balena-io/etcher/pull/4056

**Pull request closed without merging**
