### PR TITLE
Update PUBLISHING.md

### PR DESCRIPTION
**Pull request by davidlj95**
Fixed broken Hombrew cask link for etcher

### CODE REVIEW

**Comment by thundron** [comment]
@davidlj95 Could you please `rebase` instead of having the merge commit? Other than that, lgtm

**Comment by davidlj95** [comment]
@thundron done! Thanks!

**Comment by davidlj95** [comment]
@thundron rebased again to allow ff master merge

**Comment by thundron** [comment]
@davidlj95 Don't worry for now, we're doing some heavy changes to our CI, we'll warn you when ready!

**Comment by zvin** [comment]
cherry-picked in #2689, thanks @davidlj95

**Pull request closed without merging**
