### PR TITLE
minor: Add italian translation

### PR DESCRIPTION
**Pull request by bovirus**
@aethernet 

Add files for italian GUI

Please merge. Thanks.

### CODE REVIEW

**Comment by bovirus** [comment]
@aethernet 

No news about merge of this PR?

**Comment by bovirus** [comment]
@aethernet

Why so long time to apply PR regarding language?

**Comment by aethernet** [comment]
Hi, 
Thanks for the contribution, very much appreciated 🙏 

Can you squash your commits and change the title to "minor: Add italian translation" to appease the CI gods?
(you might also need to run `npm prettify` if you haven't yet.

**Comment by bovirus** [comment]
@aethernet

I change the title.

Sorry but for other operation I don't have enough competencies to do that.
If you prefer I can close this PR and open a new one with only one file change (merge all changes).

**Comment by aethernet** [comment]
@bovirus yes please do that.
It's the commit that need to be prefixed with "minor: "
:)

**Comment by bovirus** [comment]
@aethernet 

I will create a new PR.

I didn't understand about commit with "monor":. I will try.

**Pull request closed without merging**
