### PR TITLE
revert auto-update feature

### PR DESCRIPTION
**Pull request by aethernet**
Change-type: patch

### CODE REVIEW

**Comment by aethernet** [comment]
fix : https://github.com/balena-io/etcher/pull/4002#pullrequestreview-1281149027

**Comment by aethernet** [comment]
SGTM

**Comment by lurch** [comment]
Why does this also modify `package-lock.json` ?

**Comment by mcraa** [comment]
I guess @aethernet uses a node/npm version which uses lockfile 2, and it was v1 so far.
https://github.com/balena-io/etcher/actions/runs/4082554826/jobs/7038211428#step:8:32 this does not work on node 14 with lockfile v2

**Comment by aethernet** [comment]
done thanks

**Comment by aethernet** [comment]
I self-certify!

**Pull request merged**
