### PR TITLE
chore: Make the Makefile more readable

### PR DESCRIPTION
**Pull request by lurch**
Lots of small tweaks to hopefully make it more comprehensible

Change-Type: patch

### CODE REVIEW

**Comment by lurch** [comment]
Grrr, like we previously encountered in https://github.com/resin-io/etcher/pull/1258#issuecomment-300326800 and https://github.com/resin-io/etcher/pull/1390#issuecomment-300327987 , the W3 Validator service has gone down, which means all our html-lint tests, and hence all our CI builds, are failing :-(
Hopefully it won't take too long before it's back up again.

**Comment by lurch** [comment]
W3 Validator service is back up, so I restarted both the Travis and Appveyor builds on a whole bunch of PRs, which leaves OSX CI builds as the only failure, which #1897 fixes.

**Comment by lurch** [comment]
Made another tweak to better separate the notion of 'install' and 'publish'

**Comment by lurch** [comment]
Rebased to `master`

**Comment by thundron** [comment]
Closing as we changed the Makefile quite a bit, but we'll surely work on it and I'm sorry if this has been ignored for such a long time :(

**Pull request closed without merging**
