### PR TITLE
Fix Update and install Etcher with DNF instructions - documentation

### PR DESCRIPTION
**Pull request by gitexel**
Remove wrong commands `rm` from DNF update and install section

### CODE REVIEW

**Comment by lurch** [comment]
I guess this fixes #3538 ?

**Comment by gitexel** [comment]
@lurch yes

**Comment by lurch** [comment]
Did you close this accidentally?

**Comment by gitexel** [comment]
I thought there is another PR open for the same issue.

**Comment by thundron** [comment]
@gitexel I included your commit in another PR where I sanitized the commits, so that we also have one version bump instead of multiple (due to other PRs too)

**Pull request closed without merging**
