### PR TITLE
fix disabled-screensaver unhandled exception outside balena-electron env

### PR DESCRIPTION
**Pull request by aethernet**
Only makes sense on etcher-pro, polluting sentry with useless reports

Change-type: patch

### CODE REVIEW

**Review by mcraa — APPROVED** [review]

**Comment by aethernet** [comment]
lgtm

**Comment by aethernet** [comment]
@balana-ci I self-certify!

**Comment by mcraa** [comment]
And btw I already approved 😆 @aethernet

**Review by mcraa — APPROVED** [review]

**Comment by aethernet** [comment]
I thought your approval might have been "discarded" by my new commit on top of the PR

**Pull request merged**
