### PR TITLE
New parameter in webview for opt-out analytics

### PR DESCRIPTION
**Pull request by thundron**
Change-type: patch
Signed-off-by: Lorenzo Alberto Maria Ambrosi <lorenzoa@balena.io>

### CODE REVIEW

**Comment by thundron** [comment]
@dimitrisnl I don't understand, could you please comment the exact line? The condition is supposed to be in the website in order to stop tracking based on the parameter we pass here

**Comment by dimitrisnl** [comment]
I meant that passing along undefined & null values make it harder to understand. We should strip those beforehand.

I was thinking of something like

```
if (settings.get('errorReporting’) === false) {
    url.searchParams.set('optOutAnalytics', true))
}
```

**Comment by lurch** [comment]
Presumably this works for both the "during flashing" webview **and** the "flash finished" webview?

**Comment by dimitrisnl** [comment]
Yes @lurch 	It's for both of them

**Pull request merged**
