### PR TITLE
Fixes blank screen on startup

### LINKED ISSUE #3056: macOS: version. 1.5.74 app not initializing
I have a fresh install of Mojave 10.14.6 (18G103) running.
[-1580857850329.log](https://github.com/balena-io/etcher/files/4156610/-1580857850329.log)

/Applications/balenaEtcher.app/Contents/Resources/app/node_modules/raven-js/dist/raven.js:58 {"stack":"TypeError: Cannot convert undefined or null to object\n    at Function.entries (<anonymous>)\n    at Object.init (file:///Applications/balenaEtcher.app/Contents/Resources/app/generated/gui.js:3951:49)\n    at main (file:///Applications/balenaEtcher.app/Contents/Resources/app/generated/gui.js:3633:12)","message":"Cannot convert undefined or null to object"}
console.<computed> @ /Applications/balenaEtcher.app/Contents/Resources/app/node_modules/raven-js/dist/raven.js:58

Screen Shot 2020-02-04 at 3 06 35 PM
Screen Shot 2020-02-04 at 3 06 14 PM

### LINKED ISSUE #3057: Black screen when opening Etcher
- **Etcher version:** 1.5.74
- **Operating system and architecture:** Mac OS Mojave 10.14.6
- **Image flashed:** N/A
- **Do you see any meaningful error information in the DevTools?** Yes, see below

After tracing the error as the program is running, I found that in leds.ts this code seems to be throwing: (this is on startup, first time trying Etcher)
```
const ledsMapping = settings.get('ledsMapping');
for (const [drivePath, ledsPaths] of Object.entries(ledsMapping)) { // <-- this line throws
  leds.set('/dev/disk/by-path/' + drivePath, new RGBLed(ledsPaths));
}
```
settings.get(...) is returning undefined, so when the for loop tries to use Object.entries(ledsMapping), it is trying to get the entries of undefined, which causes an error.

If in devtools I set ledsMapping to an empty object `{}` the program continues to the opening menu to select image, etc. It's doing a flash operation now with that manual hack. :)

### PR DESCRIPTION
**Pull request by zomars**
Fixes #3056  #3057 #3058

### CODE REVIEW

**Comment by thundron** [comment]
Only 1 formal issue: the commit must contain at least these footers:

`Change-type: patch` - can be `major|minor|patch`)`
`Changelog-entry: ...` - usually, the commit title or a more user-readable version of it if it's too technical

For speed sake, I'm gonna cherry-pick your commit in a new PR unless you're online to fix the commit text, but nicely done nonetheless and thank you very much for the contribution!

**Comment by thundron** [comment]
Closing in favor of https://github.com/balena-io/etcher/pull/3062 , massive props to @zomars

**Comment by zomars** [comment]
@thundron it's ok! Since I didn't saw a `CONTRIBUTING.md` file I've made the PR as simple as possible.

**Comment by zomars** [comment]
Nevermind, I found the `COMMIT-GUIDELINES.md` file

**Pull request closed without merging**
