### PR TITLE
I18n conflict resolve

### PR DESCRIPTION
**Pull request by ab77**

### CODE REVIEW

**Comment by ab77** [comment]
@RoderickQiu @mcraa this PR replaces https://github.com/balena-io/etcher/pull/3790.

Please review and approve/merge when ready.

**Comment by RoderickQiu** [comment]
Oh, good, thanks!

**Comment by mcraa** [comment]
Settings modal does not open ATM.

**Review by mcraa — CHANGES_REQUESTED** [review]
Settings modal does not open atm.
Neither the flash from URL modal.

**Review by mcraa — APPROVED** [review]

**Comment by mcraa** [comment]
thanks again for the effort and patience @RoderickQiu

**Comment by RoderickQiu** [comment]
Hooray!

**Pull request merged**
